FROM ruby:3.3.10

RUN apt-get update -qq && \
    apt-get install -y \
    build-essential \
    git \
    libpq-dev \
    postgresql-client

WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

EXPOSE 3000

CMD ["bash"]